/** Stable permission keys (must match DB `permissions.key`). */

export const PERMISSIONS = {
  DASHBOARD_READ: 'dashboard.read',
  DASHBOARD_FINANCIAL: 'dashboard.financial',
  MEMBERS_READ: 'members.read',
  MEMBERS_ADD: 'members.add',
  MEMBERS_UPDATE: 'members.update',
  MEMBERS_DELETE: 'members.delete',
  MEMBERS_IMPORT: 'members.import',
  MEMBERS_EXPORT: 'members.export',
  EXPIRING_MEMBERS_VIEW: 'expiring_members.view',
  GYMS_READ: 'gyms.read',
  GYMS_ADD: 'gyms.add',
  GYMS_UPDATE: 'gyms.update',
  GYMS_DELETE: 'gyms.delete',
  EXPENSES_READ: 'expenses.read',
  EXPENSES_ADD: 'expenses.add',
  EXPENSES_UPDATE: 'expenses.update',
  EXPENSES_DELETE: 'expenses.delete',
  BANKS_READ: 'banks.read',
  BANKS_ADD: 'banks.add',
  BANKS_UPDATE: 'banks.update',
  BANKS_DELETE: 'banks.delete',
  EXPENSES_IMPORT: 'expenses.import',
  EXPENSES_EXPORT: 'expenses.export',
  TRAINERS_READ: 'trainers.read',
  TRAINERS_ADD: 'trainers.add',
  TRAINERS_UPDATE: 'trainers.update',
  TRAINERS_DELETE: 'trainers.delete',
  TRAINERS_IMPORT: 'trainers.import',
  TRAINERS_EXPORT: 'trainers.export',
  MEMBERSHIP_PLANS_READ: 'membership_plans.read',
  MEMBERSHIP_PLANS_ADD: 'membership_plans.add',
  MEMBERSHIP_PLANS_UPDATE: 'membership_plans.update',
  MEMBERSHIP_PLANS_DELETE: 'membership_plans.delete',
  MEMBERSHIP_PLANS_IMPORT: 'membership_plans.import',
  MEMBERSHIP_PLANS_EXPORT: 'membership_plans.export',
  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_MARK_AS_READ: 'notifications.mark_as_read',
  NOTIFICATIONS_MARK_ALL_AS_READ: 'notifications.mark_all_as_read',
  NOTIFICATIONS_DELETE: 'notifications.delete',
  USERS_READ: 'users.read',
  USERS_ADD: 'users.add',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_MANAGE_PERMISSIONS: 'users.manage_permissions',
  MY_ACCOUNT_VIEW: 'my_account.view',
  MY_ACCOUNT_UPDATE: 'my_account.update',
  SYSTEM_MANAGE_ROLES: 'system.manage_roles',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export type PermissionDefinition = {
  key: PermissionKey;
  description: string;
};

export const PERMISSION_DEFINITIONS: readonly PermissionDefinition[] = [
  { key: PERMISSIONS.DASHBOARD_READ, description: "View dashboard" },
  { key: PERMISSIONS.DASHBOARD_FINANCIAL, description: "View financial dashboard analytics" },
  { key: PERMISSIONS.MEMBERS_READ, description: "View members" },
  { key: PERMISSIONS.MEMBERS_ADD, description: "Create members" },
  { key: PERMISSIONS.MEMBERS_UPDATE, description: "Update members" },
  { key: PERMISSIONS.MEMBERS_DELETE, description: "Delete members" },
  { key: PERMISSIONS.MEMBERS_IMPORT, description: "Import members data" },
  { key: PERMISSIONS.MEMBERS_EXPORT, description: "Export members data" },
  { key: PERMISSIONS.EXPIRING_MEMBERS_VIEW, description: "View expiring members" },
  { key: PERMISSIONS.GYMS_READ, description: "View gyms" },
  { key: PERMISSIONS.GYMS_ADD, description: "Create gyms" },
  { key: PERMISSIONS.GYMS_UPDATE, description: "Update gyms" },
  { key: PERMISSIONS.GYMS_DELETE, description: "Delete gyms" },
  { key: PERMISSIONS.EXPENSES_READ, description: "View expenses" },
  { key: PERMISSIONS.EXPENSES_ADD, description: "Create expenses" },
  { key: PERMISSIONS.EXPENSES_UPDATE, description: "Update expenses" },
  { key: PERMISSIONS.EXPENSES_DELETE, description: "Delete expenses" },
  { key: PERMISSIONS.BANKS_READ, description: "View banks" },
  { key: PERMISSIONS.BANKS_ADD, description: "Create banks" },
  { key: PERMISSIONS.BANKS_UPDATE, description: "Update banks" },
  { key: PERMISSIONS.BANKS_DELETE, description: "Delete banks" },
  { key: PERMISSIONS.EXPENSES_IMPORT, description: "Import expenses data" },
  { key: PERMISSIONS.EXPENSES_EXPORT, description: "Export expenses data" },
  { key: PERMISSIONS.TRAINERS_READ, description: "View trainers and staff" },
  { key: PERMISSIONS.TRAINERS_ADD, description: "Create trainers and staff" },
  { key: PERMISSIONS.TRAINERS_UPDATE, description: "Update trainers and staff" },
  { key: PERMISSIONS.TRAINERS_DELETE, description: "Delete trainers and staff" },
  { key: PERMISSIONS.TRAINERS_IMPORT, description: "Import trainers and staff data" },
  { key: PERMISSIONS.TRAINERS_EXPORT, description: "Export trainers and staff data" },
  { key: PERMISSIONS.MEMBERSHIP_PLANS_READ, description: "View membership plans" },
  { key: PERMISSIONS.MEMBERSHIP_PLANS_ADD, description: "Create membership plans" },
  { key: PERMISSIONS.MEMBERSHIP_PLANS_UPDATE, description: "Update membership plans" },
  { key: PERMISSIONS.MEMBERSHIP_PLANS_DELETE, description: "Delete membership plans" },
  { key: PERMISSIONS.MEMBERSHIP_PLANS_IMPORT, description: "Import membership plans data" },
  { key: PERMISSIONS.MEMBERSHIP_PLANS_EXPORT, description: "Export membership plans data" },
  { key: PERMISSIONS.NOTIFICATIONS_READ, description: "View notifications" },
  { key: PERMISSIONS.NOTIFICATIONS_MARK_AS_READ, description: "Mark notifications as read" },
  { key: PERMISSIONS.NOTIFICATIONS_MARK_ALL_AS_READ, description: "Mark all notifications as read" },
  { key: PERMISSIONS.NOTIFICATIONS_DELETE, description: "Delete notifications" },
  { key: PERMISSIONS.USERS_READ, description: "View users" },
  { key: PERMISSIONS.USERS_ADD, description: "Create users" },
  { key: PERMISSIONS.USERS_UPDATE, description: "Update users" },
  { key: PERMISSIONS.USERS_DELETE, description: "Delete users" },
  { key: PERMISSIONS.USERS_MANAGE_PERMISSIONS, description: "Manage user permissions" },
  { key: PERMISSIONS.SYSTEM_MANAGE_ROLES, description: "Manage roles" },
  { key: PERMISSIONS.MY_ACCOUNT_VIEW, description: "View my account" },
  { key: PERMISSIONS.MY_ACCOUNT_UPDATE, description: "Update my account" },
];

export const ALL_PERMISSION_KEYS: readonly PermissionKey[] = PERMISSION_DEFINITIONS.map(
  (permission) => permission.key
);
